-- ============================================================================
-- CASA SMOKE Y ARTE OT - VIP / TARJETAS NFC NTAG215 POR UID (PC/SC)
-- Migracion incremental para ejecutar DESPUES de docs/vip-membership-setup.sql
--
-- Objetivo:
--   - Vincular el UID fisico de una NTAG215 a la credencial VIP activa.
--   - Evitar que una misma tarjeta activa pertenezca a dos membresias.
--   - Validar, registrar entrada y registrar salida usando el UID.
--   - Conservar auditoria de vinculaciones/reemplazos/desvinculaciones.
--   - No almacenar datos personales dentro de la tarjeta NFC.
--
-- Lector probado en Windows:
--   Generic Contactless Card Reader 0 / PC-SC CCID
--   USB VID_2CE3 / PID_9567
--
-- IMPORTANTE:
--   Esta migracion NO permite que un navegador de Vercel acceda directamente
--   al lector PC/SC de Windows. El helper local de Windows leera el UID y la
--   pagina enviara ese UID a estas RPC de Supabase.
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1. Ampliar la credencial NFC existente con los datos tecnicos de la tarjeta
-- ----------------------------------------------------------------------------

alter table public.vip_access_tokens
  add column if not exists card_uid text,
  add column if not exists card_type text,
  add column if not exists card_bound_at timestamptz,
  add column if not exists card_bound_by uuid references auth.users(id) on delete set null,
  add column if not exists card_reader text,
  add column if not exists card_last_seen_at timestamptz,
  add column if not exists card_scan_count bigint not null default 0;

-- Solo una credencial ACTIVA puede usar un UID determinado.
create unique index if not exists vip_one_active_card_uid
  on public.vip_access_tokens (upper(card_uid))
  where is_active = true and card_uid is not null;

comment on column public.vip_access_tokens.card_uid is
  'UID fisico normalizado de la tarjeta NFC. Para NTAG215 se esperan 7 bytes = 14 caracteres hexadecimales.';
comment on column public.vip_access_tokens.card_type is
  'Tipo de tarjeta fisica; para el flujo actual se usa NTAG215.';
comment on column public.vip_access_tokens.card_reader is
  'Identificacion informativa del lector usado al vincular la tarjeta.';
comment on column public.vip_access_tokens.card_last_seen_at is
  'Ultima lectura administrativa del UID a traves del control de acceso.';

-- ----------------------------------------------------------------------------
-- 2. Auditoria de tarjetas fisicas
-- ----------------------------------------------------------------------------

create table if not exists public.vip_card_audit (
  id bigint generated by default as identity primary key,
  membership_id uuid not null references public.vip_memberships(id) on delete cascade,
  token_id uuid references public.vip_access_tokens(id) on delete set null,
  card_uid text not null,
  action text not null check (action in ('bound', 'replaced', 'unbound')),
  card_type text,
  reader_label text,
  performed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists vip_card_audit_membership_created
  on public.vip_card_audit (membership_id, created_at desc);

alter table public.vip_card_audit enable row level security;

drop policy if exists "vip_card_audit_admin_read" on public.vip_card_audit;
create policy "vip_card_audit_admin_read"
  on public.vip_card_audit for select
  to authenticated
  using (public.vip_is_admin());

-- Las modificaciones se hacen exclusivamente mediante RPC SECURITY DEFINER.
revoke all on public.vip_card_audit from anon;
revoke insert, update, delete on public.vip_card_audit from authenticated;
grant select on public.vip_card_audit to authenticated;

comment on table public.vip_card_audit is
  'Historial administrativo de vinculacion de UID NFC; no guarda datos personales del cliente.';

-- ----------------------------------------------------------------------------
-- 3. Normalizacion del UID
-- ----------------------------------------------------------------------------

create or replace function public.vip_normalize_card_uid(p_card_uid text)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  v_uid text;
begin
  -- Acepta formatos como 04:A1:B2:C3:D4:E5:F6 o 04-A1-B2-C3-D4-E5-F6.
  v_uid := upper(regexp_replace(coalesce(trim(p_card_uid), ''), '[^0-9A-Fa-f]', '', 'g'));

  if v_uid !~ '^[0-9A-F]{14}$' then
    raise exception 'UID NFC invalido. Para NTAG215 se esperan 7 bytes (14 caracteres hexadecimales).';
  end if;

  return v_uid;
end;
$$;

revoke all on function public.vip_normalize_card_uid(text) from public;
grant execute on function public.vip_normalize_card_uid(text) to authenticated;

-- ----------------------------------------------------------------------------
-- 4. Vincular / reemplazar tarjeta desde el panel administrativo
-- ----------------------------------------------------------------------------

create or replace function public.vip_admin_bind_card_uid(
  p_membership_id uuid,
  p_card_uid text,
  p_card_type text default 'NTAG215',
  p_reader_label text default 'PC/SC VID_2CE3 PID_9567'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid text;
  v_membership public.vip_memberships;
  v_token public.vip_access_tokens;
  v_previous_uid text;
  v_action text;
begin
  if not public.vip_is_admin() then
    raise exception 'Acceso administrativo requerido para vincular una tarjeta NFC.';
  end if;

  v_uid := public.vip_normalize_card_uid(p_card_uid);

  select * into v_membership
  from public.vip_memberships
  where id = p_membership_id
  for update;

  if not found then
    raise exception 'Membresia VIP no encontrada.';
  end if;

  -- No se entrega una credencial de acceso antes de completar los controles.
  if v_membership.status <> 'active' then
    raise exception 'La membresia debe estar activa antes de vincular la tarjeta NFC.';
  end if;

  if not v_membership.adult_verified then
    raise exception 'Debe completarse la verificacion administrativa de identidad antes de vincular la tarjeta.';
  end if;

  if exists (
    select 1
    from public.vip_access_tokens t
    where t.is_active = true
      and upper(t.card_uid) = v_uid
      and t.membership_id <> p_membership_id
  ) then
    raise exception 'Esta tarjeta NFC ya esta vinculada a otra membresia activa.';
  end if;

  select * into v_token
  from public.vip_access_tokens
  where membership_id = p_membership_id
    and is_active = true
  order by issued_at desc
  limit 1
  for update;

  if not found then
    insert into public.vip_access_tokens (membership_id, created_by)
    values (p_membership_id, auth.uid())
    returning * into v_token;
  end if;

  v_previous_uid := v_token.card_uid;
  v_action := case
    when v_previous_uid is null then 'bound'
    when upper(v_previous_uid) = v_uid then 'bound'
    else 'replaced'
  end;

  update public.vip_access_tokens
  set
    card_uid = v_uid,
    card_type = coalesce(nullif(trim(p_card_type), ''), 'NTAG215'),
    card_bound_at = now(),
    card_bound_by = auth.uid(),
    card_reader = nullif(trim(p_reader_label), '')
  where id = v_token.id
  returning * into v_token;

  insert into public.vip_card_audit (
    membership_id,
    token_id,
    card_uid,
    action,
    card_type,
    reader_label,
    performed_by
  ) values (
    p_membership_id,
    v_token.id,
    v_uid,
    v_action,
    v_token.card_type,
    v_token.card_reader,
    auth.uid()
  );

  return jsonb_build_object(
    'membership_id', p_membership_id,
    'token_id', v_token.id,
    'token', v_token.token,
    'card_uid', v_token.card_uid,
    'card_type', v_token.card_type,
    'card_bound_at', v_token.card_bound_at,
    'action', v_action
  );
end;
$$;

-- ----------------------------------------------------------------------------
-- 5. Desvincular una tarjeta sin borrar la membresia ni la credencial web
-- ----------------------------------------------------------------------------

create or replace function public.vip_admin_unbind_card_uid(p_membership_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token public.vip_access_tokens;
  v_uid text;
begin
  if not public.vip_is_admin() then
    raise exception 'Acceso administrativo requerido para desvincular una tarjeta NFC.';
  end if;

  select * into v_token
  from public.vip_access_tokens
  where membership_id = p_membership_id
    and is_active = true
    and card_uid is not null
  order by issued_at desc
  limit 1
  for update;

  if not found then
    raise exception 'La membresia no tiene una tarjeta NFC fisica vinculada.';
  end if;

  v_uid := v_token.card_uid;

  insert into public.vip_card_audit (
    membership_id,
    token_id,
    card_uid,
    action,
    card_type,
    reader_label,
    performed_by
  ) values (
    p_membership_id,
    v_token.id,
    v_uid,
    'unbound',
    v_token.card_type,
    v_token.card_reader,
    auth.uid()
  );

  update public.vip_access_tokens
  set
    card_uid = null,
    card_type = null,
    card_bound_at = null,
    card_bound_by = null,
    card_reader = null
  where id = v_token.id;
end;
$$;

-- ----------------------------------------------------------------------------
-- 6. Validar acceso directamente por UID del lector PC/SC
-- ----------------------------------------------------------------------------

create or replace function public.vip_validate_access_by_uid(p_card_uid text)
returns table (
  membership_id uuid,
  member_number text,
  member_name text,
  status text,
  adult_verified boolean,
  starts_at timestamptz,
  ends_at timestamptz,
  visits_used bigint,
  visit_limit integer,
  currently_inside boolean,
  access_allowed boolean,
  reason text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid text;
  v_token uuid;
  v_token_id uuid;
begin
  if not public.vip_is_admin() then
    raise exception 'Inicia sesion como administrador para validar el acceso.';
  end if;

  v_uid := public.vip_normalize_card_uid(p_card_uid);

  select t.token, t.id
  into v_token, v_token_id
  from public.vip_access_tokens t
  where t.is_active = true
    and upper(t.card_uid) = v_uid
  limit 1;

  if v_token is null then
    raise exception 'Tarjeta NFC no vinculada o inactiva.';
  end if;

  update public.vip_access_tokens
  set
    card_last_seen_at = now(),
    card_scan_count = card_scan_count + 1
  where id = v_token_id;

  return query
  select * from public.vip_validate_access(v_token);
end;
$$;

-- ----------------------------------------------------------------------------
-- 7. Entrada y salida por UID reutilizando las reglas VIP existentes
-- ----------------------------------------------------------------------------

create or replace function public.vip_check_in_by_uid(p_card_uid text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid text;
  v_token uuid;
begin
  if not public.vip_is_admin() then
    raise exception 'Acceso administrativo requerido.';
  end if;

  v_uid := public.vip_normalize_card_uid(p_card_uid);

  select t.token into v_token
  from public.vip_access_tokens t
  where t.is_active = true
    and upper(t.card_uid) = v_uid
  limit 1;

  if v_token is null then
    raise exception 'Tarjeta NFC no vinculada o inactiva.';
  end if;

  return public.vip_check_in(v_token, 'nfc');
end;
$$;

create or replace function public.vip_check_out_by_uid(p_card_uid text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid text;
  v_token uuid;
begin
  if not public.vip_is_admin() then
    raise exception 'Acceso administrativo requerido.';
  end if;

  v_uid := public.vip_normalize_card_uid(p_card_uid);

  select t.token into v_token
  from public.vip_access_tokens t
  where t.is_active = true
    and upper(t.card_uid) = v_uid
  limit 1;

  if v_token is null then
    raise exception 'Tarjeta NFC no vinculada o inactiva.';
  end if;

  perform public.vip_check_out(v_token);
end;
$$;

-- ----------------------------------------------------------------------------
-- 8. Permisos RPC para Supabase / PostgREST
-- Cada funcion vuelve a comprobar vip_is_admin() internamente.
-- ----------------------------------------------------------------------------

revoke all on function public.vip_admin_bind_card_uid(uuid, text, text, text) from public;
revoke all on function public.vip_admin_unbind_card_uid(uuid) from public;
revoke all on function public.vip_validate_access_by_uid(text) from public;
revoke all on function public.vip_check_in_by_uid(text) from public;
revoke all on function public.vip_check_out_by_uid(text) from public;

grant execute on function public.vip_admin_bind_card_uid(uuid, text, text, text) to authenticated;
grant execute on function public.vip_admin_unbind_card_uid(uuid) to authenticated;
grant execute on function public.vip_validate_access_by_uid(text) to authenticated;
grant execute on function public.vip_check_in_by_uid(text) to authenticated;
grant execute on function public.vip_check_out_by_uid(text) to authenticated;

-- Solicita a PostgREST/Supabase que refresque el esquema de RPC.
notify pgrst, 'reload schema';

commit;

-- ============================================================================
-- COMPROBACION DESPUES DE EJECUTAR
-- ============================================================================
-- 1) Ver columnas NFC agregadas:
-- select column_name, data_type
-- from information_schema.columns
-- where table_schema = 'public'
--   and table_name = 'vip_access_tokens'
--   and column_name like 'card_%'
-- order by ordinal_position;
--
-- 2) Ver tarjetas vinculadas (solo desde SQL Editor/admin):
-- select membership_id, card_uid, card_type, card_bound_at, card_reader,
--        card_last_seen_at, card_scan_count
-- from public.vip_access_tokens
-- where is_active = true
-- order by issued_at desc;
--
-- 3) Las llamadas que usara el panel son:
--    vip_admin_bind_card_uid(membership_id, uid, 'NTAG215', lector)
--    vip_validate_access_by_uid(uid)
--    vip_check_in_by_uid(uid)
--    vip_check_out_by_uid(uid)
--    vip_admin_unbind_card_uid(membership_id)
-- ============================================================================
